export const types = {
  //To get community
  GET_COMMUNITY_PENDING: "GET_COMMUNITY_PENDING",
  GET_COMMUNITY_SUCCESS: "GET_COMMUNITY_SUCCESS",
  GET_COMMUNITY_ERROR: "GET_COMMUNITY_ERROR",
  GET_COMMUNITY_HAS_MORE: "GET_COMMUNITY_HAS_MORE",

  //To post a community
  POST_COMMUNITY_PENDING: "POST_COMMUNITY_PENDING",
  POST_COMMUNITY_SUCCESS: "POST_COMMUNITY_SUCCESS",
  POST_COMMUNITY_ERROR: "POST_COMMUNITY_ERROR",

  //To reset the state to default
  RESET_STATE: "RESET_STATE",
};
